version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-1604:202004-01
    working_directory: ~/quarkus-showcase
    steps:
      - checkout

      - restore_cache:
          key: quarkus-showcase-{{ checksum "pom.xml" }}

      - run:
          name: fetch dependencies
          command: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: quarkus-showcase-{{ checksum "pom.xml" }}

      - run:
          name: build and tests
          command: mvn -B clean verify -Ddockerfile.username=$DOCKER_USER -Ddockerfile.password=$DOCKER_PASS sonar:sonar --fail-never

      - store_test_results:
          path: target/surefire-reports

workflows:
  main:
    jobs:
      - build:
          context: Credentials